
package swSoap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Sat Jan 16 00:11:58 CET 2016
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "UpdateEventResponse", namespace = "http://swSoap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateEventResponse", namespace = "http://swSoap/")

public class UpdateEventResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

