
package swSoap.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * Sat Jan 16 00:11:58 CET 2016
 * Generated source version: 2.7.14.redhat-1
 */

@XmlRootElement(name = "UpdateEvent", namespace = "http://swSoap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateEvent", namespace = "http://swSoap/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4", "arg5"})

public class UpdateEvent {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private int arg1;
    @XmlElement(name = "arg2")
    private int arg2;
    @XmlElement(name = "arg3")
    private java.lang.String arg3;
    @XmlElement(name = "arg4")
    private java.lang.String arg4;
    @XmlElement(name = "arg5")
    private java.lang.String arg5;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public int getArg1() {
        return this.arg1;
    }

    public void setArg1(int newArg1)  {
        this.arg1 = newArg1;
    }

    public int getArg2() {
        return this.arg2;
    }

    public void setArg2(int newArg2)  {
        this.arg2 = newArg2;
    }

    public java.lang.String getArg3() {
        return this.arg3;
    }

    public void setArg3(java.lang.String newArg3)  {
        this.arg3 = newArg3;
    }

    public java.lang.String getArg4() {
        return this.arg4;
    }

    public void setArg4(java.lang.String newArg4)  {
        this.arg4 = newArg4;
    }

    public java.lang.String getArg5() {
        return this.arg5;
    }

    public void setArg5(java.lang.String newArg5)  {
        this.arg5 = newArg5;
    }

}

